### ISSUE TITLE
Doesn't work on Nuxtjs v3.x,  Official Example not working.

### ISSUE THREAD

**Issue by zeeklog** [I2Djs/pdf-frame#18]
1. Error:
![image](https://github.com/user-attachments/assets/97b39700-35fd-4684-a22e-4ca7c267475a)
[nitro] [uncaughtException] TypeError: performance.markResourceTiming is not a function

2. Nuxt Page Demo:
```

<template>
  <div class="canvasParentContainer">
    <pdfFrame type="canvas" width="595" height="841" src="123.pdf"> </pdfFrame>
  </div>
</template>
<script setup></script>
```

3. nuxt.config.js
```
export default defineNuxtConfig({
  modules: [
    '@i2d/nuxt-pdf-frame',
  ]
})
```

**Comment by nswamy14** [comment]
@zeeklog  This is not a bug... Please go through the stackblitz example.
https://stackblitz.com/~/github.com/I2Djs/pdf-frame-showcase/tree/stackBlitzShowcase?file=nuxt.config.ts
