### ISSUE TITLE
<i-text> underlined?

### ISSUE THREAD

**Issue by jfrey88** [I2Djs/pdf-frame#19]
Hello, is it possible to have <i-text> underlined?

**Comment by nswamy14** [comment]
@jfrey88 , Text decoration is not supported in the current version.

This will come in the next version which is planned for this weekend.  Text decorations: Underline, Link, Anchor, Goto, Strike, Oblique.. etc.

**Comment by nswamy14** [comment]
@jfrey88  Please check the following text-decoration example : [Text-Decoration](https://www.pdf-frame.org/?title=PDF:+Text+Decorations&type=pdf)
