### ISSUE TITLE
Download function

### ISSUE THREAD

**Issue by afuentesdp90** [I2Djs/pdf-frame#20]
Can I download the pdf into a file?

**Comment by nswamy14** [comment]
@afuentesdp90  refer to this example : https://www.pdf-frame.org/?title=PDF:+Blob&type=pdf

**Comment by afuentesdp90** [comment]
Thank you!! It was there? Or is new one example?

**Comment by nswamy14** [comment]
It was already there. Closing issue as it is resolved.
